import { Web3Auth } from "@web3auth/modal";

let web3auth: Web3Auth | null = null;

export async function initWeb3Auth() {
  if (web3auth) return web3auth;

  web3auth = new Web3Auth({
    clientId: process.env.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID!, // Canopi's Client ID
    web3AuthNetwork: "sapphire_mainnet",
  });

  await web3auth.init();
  return web3auth;
}

export async function login() {
  const web3auth = await initWeb3Auth();

  // Connect to Web3Auth (user authenticates with Google/X/email)
  const provider = await web3auth.connect();

  // Get user info (varies by login method)
  const userInfo = await web3auth.getUserInfo();

  // Social Login (Google/X/Email):
  // - verifierId: unique Web3Auth identifier
  // - email: user email ✅
  // - name: user name ✅
  // - profileImage: avatar URL ✅
  // - typeOfLogin: 'google', 'twitter', 'email_passwordless'

  // Web3 Wallet Login (MetaMask/WalletConnect):
  // - verifierId: wallet address (e.g., "wallet_0x1234...")
  // - email: null ❌
  // - name: null ❌
  // - profileImage: null ❌
  // - typeOfLogin: 'wallet'

  // Get wallet address
  const accounts = await provider.request({ method: 'eth_accounts' });
  const evmAddress = accounts[0];
  // For Social Login: Generated by Web3Auth
  // For Wallet Login: From user's connected wallet

  // Optional: Get Solana address (if Solana configured)
  let solanaAddress = null;
  if (web3auth.chainNamespace === 'solana') {
    const solAccounts = await provider.request({ method: 'getAccounts' });
    solanaAddress = solAccounts[0];
  }

  // Send to RFC backend
  const response = await fetch('/api/auth/web3auth', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      verifierId: userInfo.verifierId,
      typeOfLogin: userInfo.typeOfLogin, // Important: 'google', 'wallet', etc.
      email: userInfo.email, // null for wallet login
      name: userInfo.name, // null for wallet login
      profileImage: userInfo.profileImage, // null for wallet login
      evmAddress, // Always available (generated or from wallet)
      solanaAddress, // Optional: if Solana configured
    }),
  });

  const { user } = await response.json();

  // RFC manages its own session (no JWT tokens needed)
  return { user };
}

export async function logout() {
  const web3auth = await initWeb3Auth();
  await web3auth.logout();

  // Clear RFC session
  await fetch('/api/auth/logout', { method: 'POST' });
}